### ISSUE TITLE
add calendar pagination

### ISSUE THREAD

**Issue by aroman** [AEPi-AK/autosteward#5]

**Comment by afrieder** [comment]
Specifically:
Adding a new week, selecting a Monday from a calendar to anchor the schedule.

**Comment by aroman** [comment]
i wasn't planning on having weeks being explicitly "created". I was planning on just having them be dynamically generated. Whether you actually assign anyone to slots on that week determines whether it's used or not.

Does that make sense?

**Comment by afrieder** [comment]
How will that interact with the red coloring? Will it look back to the last week, or the last "used" week?

**Comment by aroman** [comment]
good question. i had in mind just looking at the previous week (i.e. subtract 7 calendar days). should it be the last used week?

**Comment by afrieder** [comment]
Yeah, last used week sounds better.
